myshop_2/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop_2/myshop_2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^account/', include('account.urls')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop_2/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url('^test', views.test, name = 'test'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]

myshop_2/shop/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categorys'
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                        args=[self.slug])
    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products', blank=True)
    description = models.TextField(blank=True)
    maxResolution = models.CharField(max_length=200, blank=True)
    maxExcerpt = models.PositiveIntegerField(default = 0)
    megapixels = models.FloatField(default = 2)
    rating = models.FloatField(default = 3)
    countRating = models.FloatField(default = 1)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
    def get_absolute_url(self):
        return reverse('shop:product_detail',
                        args=[self.id, self.slug])
    def __str__(self):
        return self.name


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250, db_index=True)
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField(blank=True, null = True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True,  null = True)
    updated = models.DateTimeField(auto_now=True, null = True)
    rating = models.FloatField(default = 0)
    product = models.ForeignKey(Product, related_name='blog_posts', blank = True, null = True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

myshop_2/shop/forms.py
from django import forms

from .models import Post, Product

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body', 'rating')


CHOICES = (
    (0, 'a'),
    (1, 'b'),
    (2, 'c'),
)

class SortForm(forms.Form):
    letters = forms.MultipleChoiceField(
            choices=CHOICES, 
            label="", 
            required=False) 


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

class UserForm(forms.Form):
    name = forms.CharField(label="name")
    age = forms.IntegerField(label="age")


class listClass(forms.Form):
    listC = ("Sony", "Canon", "Nikon", "Olympus", "Fujifilm")

    listRes = ("6000x4000", "5472x3648", "5184x3456", "4608x3456", "4592x3448", "3840x2160")

myshop_2/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, Post
from .forms import PostForm, SortForm, ContactForm, UserForm, listClass
from django.http import HttpResponse
from cart.forms import CartAddProductForm


def sortByRating(inputStr):
    return 5 - float(inputStr.rating)

def product_list(request, category_slug=None):
    print (request.method)

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        cat = request.POST.getlist("categorys")
        res = request.POST.getlist("resolution")
        minPrice = int(request.POST.get("minPrice"))
        print (res)
        maxPrice = int(request.POST.get("maxPrice"))
        expres = int(request.POST.get("expre"))
        megapixels = float(request.POST.get("megapixels"))
        prod = Product.objects.filter(available=True)
        prod_list = []
        for p in prod:
            print (p)
            if maxPrice >= int(p.price) >= minPrice:
                print ("price")
                if str(p.category) in cat or not cat:
                    print ("cat")
                    if str(p.maxResolution) in res or not res:
                        print ("res is ok")
                        if int(p.maxExcerpt) > expres and float(p.megapixels) > megapixels:
                            print ("exc")
                            prod_list.append(p)
        print (prod_list)
        prod_list.sort(key=sortByRating)
    else:
        prod_list = Product.objects.filter(available=True)
        prod_list = prod_list.extra(order_by = ['-rating'])

#    prod_list.sort(key=sortByRating)
    category = None
    categories = Category.objects.all()

    lists = listClass()
    print ("listsClass", lists)
    # if this is a POST request we need to process the form data
    return render(request,
                  'shop/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': prod_list,
                   'lists': lists})

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
#    posts = Post.objects.filter(product = product)
    posts = product.blog_posts.all()
    cart_product_form = CartAddProductForm()
    #post_form = PostForm(data=request.POST)
    print (request.method)
    if request.method == 'POST':
        title = str(request.POST.get("title"))
        body = str(request.POST.get("body"))
        rating = float(request.POST.get("rating"))
        new_post = Post(title = title, author = request.user, body = body, rating = rating, product = product)

        old_rating = product.rating * product.countRating
        old_rating += rating
        product.countRating += 1
        product.rating = old_rating / product.countRating
        product.save()
        new_post.save()
        print (title, body, rating)
        print (product.blog_posts)
        # A comment was posted
        post_form = PostForm(data=request.POST)
        if post_form.is_valid():
            # Create Comment object but don't save to database yet
            """
            new_post = post_form.save(commit=False)
            # Assign the current post to the comment
            new_post.product = product
            print (post_form.cleaned_data['title'])
            rating = product.rating * product.countRating
            selfRating = post_form.cleaned_data['rating']
            rating += selfRating
            product.countRating += 1
            product.rating = rating / product.countRating
            product.save()
            # Save the comment to the database
            print (new_post)
            new_post.author = request.user
            new_post.save()
            """
    else:
        post_form = PostForm()
        print ("nw post")
    return render(request,
                  'shop/detail.html',
                  {'product': product,
                  'posts': posts,
                  'post_form': post_form,
                  'cart_product_form': cart_product_form})



def test(request):
    userform = UserForm(field_order = ["age", "name"])
    print (request.POST.get("name"))
    print (request.POST.get("age"))
    return render(request, "shop/test.html", {"form": userform})

myshop_2/shop/templates/shop/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="product-detail">
      <div class="media" style = "background-color: Gainsboro;">
          <a href="#">
              <img style="width: 25rem;margin-top: 8%;margin-left: 5%;" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" class="rounded">
          </a>
      <div class="media-body" style = "margin-left: 4%;">
      <h3>{{ product.name }}</h3>
        <h3><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h3>
        <p class="price">₽{{ product.price }}</p>
        {{ product.description|linebreaks }}
      <div class="media-body">
    <h5 class="media-heading">Max.Resolution:{{ product.maxResolution }}</h5>
    <h5 class="media-heading">Max.Excerpt:{{ product.maxExcerpt }}</h5>
    <h5 class="media-heading">megapixels:{{ product.megapixels }}</h5>
    <h5 class="media-heading">rating:{{ product.rating }}</h5>
  </div>
  <form action="{% url "cart:cart_add" product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Add to cart">
</form>
</div>
</div>
</div>

    <h1>Comments</h1>
    {% for post in posts %}
    <div class="media w3-border w3-border-black" style = "background: Aquamarine">
        <div class ="w3-border w3-border-black w3-bottombar w3-rightbar" style = "background: LightGreen;">
        <h3>
            <a style = "vertical-align: top;">{{ post.author }}</a>
        </h3>
    </div>
        <div class="media-body">
            <p class="date">
                <h3> {{ post.title }} </h3>
                Published {{ post.publish }}
            </p>
            {{ post.body|truncatewords:30|linebreaks }}
            rating:{{ post.rating }}/5
        </div>
    </div>

    {% endfor %}

    <form action="." method="post" style= "background: LightGreen;width: 45rem;">
        {% csrf_token %}
            <div class="w3-container w3-blue"  style = "width: 45rem;">
  <h2>New Comment</h2>
</div>

  <p>
  <label>Title</label>
  <input class="w3-input" name = "title" type="text" style = "width: 44rem;"></p>
  <p>
  <label>Comment</label>
  <textarea class="w3-input" name = "body" type="text" style="height: 5rem;resize: none;width: 44rem;"></textarea>
  <p>
    <div class="slidecontainer">
  <input type="range" min="0" max="5" value="2.5" step="0.5" class="slider" name = "rating" id="myRange"style = "width: 44rem;">
  <p>Rating: <span id="demo"></span></p>
</div>
</p>
        <p><input type="submit" value="Add comment"></p>
    </form>

<script>
var slider = document.getElementById("myRange");
var output = document.getElementById("demo");
output.innerHTML = slider.value;

slider.oninput = function() {
  output.innerHTML = this.value;
}
</script>
{% endblock %}

myshop_2/shop/templates/shop/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="w3-sidebar w3-bar-block w3-large w3-light-grey" style="width:15%;">
        <small>
        <form method="POST" class="form-inline">
        {% csrf_token %}
        <a class="w3-bar-item">
        <div class="w3-dropdown-hover">
            <button class="w3-button w3-green">Category</button>
            <div class="w3-dropdown-content w3-bar-block w3-border">
                {% for d in lists.listC %}
                <a class="w3-bar-item w3-button">
                <h5><input type="checkbox" name="categorys" value="{{ d }}" />{{ d }}</h5>
                </a>
                {% endfor %}

            </div>
        </div>
    </a>
    <a class="w3-bar-item">
        <div class="w3-dropdown-hover">
            <button class="w3-button w3-green">Resolution</button>
            <div class="w3-dropdown-content w3-bar-block w3-border">
                {% for d in lists.listRes %}
                <a class="w3-bar-item w3-button">
                <h5><input type="checkbox" name="resolution" value="{{ d }}" />{{ d }}</h5>
                </a>
                {% endfor %}

            </div>
        </div>
    </a>
    <a class="w3-bar-item">
        ₽ min Price
    </a>
    <div class="col">
      <input type="text" class="form-control" placeholder="min.price" value = '6000' name = "minPrice" style="width:160px;">
    </div>
    <a class="w3-bar-item">
        ₽ max Price
    </a>
    <div class="col">
      <input type="text" class="form-control" placeholder="max.price" value = "1000000" name = "maxPrice"style="width:160px;">
    </div>
    <a class="w3-bar-item">
        Excerption
    </a>
    <div class="col">
      <input type="text" class="form-control" placeholder="Excerpt" value = "0" name = "expre"style="width:160px;">
    </div>
    <a class="w3-bar-item">
        Megapixels
    </a>
    <div class="col">
      <input type="text" class="form-control" placeholder="Megapixels" value = "2" name = "megapixels"style="width:160px;">
    </div>
        <input type="submit" value="Search" >
        </form>

</div>
</small>
<div style="margin-left:7%">

<div class="w3-container">
    <div id="content" name="content" class="main">
        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        {% for product in products %}
            <div class="row">
                <div class="col-sm-6 col-md-3">
                    <div class="card" style="width: 18rem;background-color: Gainsboro;height: 380px;">
                        <a href="{{ product.get_absolute_url }}">
                            <img style="width: 17rem; margin-left: 2%;margin-top: 2%;" 
                            src="{{ MEDIA_URL }}{{ product.image.url }}"class="rounded"/>
                        </a>
                        <div class="card-body">
                            <h5 class="card-title" ><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h5>
                            <p class="card-text"><p>price:₽ {{ product.price }}</p></p>
                            <p class="card-text"><p>rating:{{ product.rating }}/5</p></p>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}

myshop_2/shop/templates/shop/test.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Test
{% endblock %}
{% block content %}

<div class="w3-container">
  <h2>Dropdown Button</h2>
  <p>Move the mouse over the button to open the dropdown content.</p>
  <div class="w3-dropdown-hover">
    <button class="w3-button w3-black">Hover Over Me!</button>
    <div class="w3-dropdown-content w3-bar-block w3-border">
      <a href="#" class="w3-bar-item w3-button">Link 1</a>
      <a href="#" class="w3-bar-item w3-button">Link 2</a>
      <a href="#" class="w3-bar-item w3-button">Link 3</a>
    </div>
  </div>
</div>

{% endblock %}

myshop_2/shop/templates/shop/test_2.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.vertical-menu {
    width: 200px;
    height: 150px;
    overflow-y: auto;
}

.vertical-menu a {
    background-color: #eee;
    color: black;
    display: block;
    padding: 12px;
    text-decoration: none;
}

.vertical-menu a:hover {
    background-color: #ccc;
}

.vertical-menu a.active {
    background-color: #4CAF50;
    color: white;
}
</style>
</head>
<body>

<h1>Vertical Scroll Menu</h1>

<div class="vertical-menu">
  <a href="#" class="active">Home</a>
  <a href="#">Link 1</a>
  <a href="#">Link 2</a>
  <a href="#">Link 3</a>
  <a href="#">Link 4</a>
  <a href="#">Link 5</a>
  <a href="#">Link 6</a>
  <a href="#">Link 7</a>
  <a href="#">Link 8</a>
  <a href="#">Link 9</a>
  <a href="#">Link 10</a>
</div>

</body>
</html>